[env]
_.file = ".env"

[tools]
"make" = "4.4.1"
"node" = "24"
"go" = "1.27.1"
"go:go.uber.org/mock/mockgen" = "v0.6.0"
"go:golang.org/x/vuln/cmd/govulncheck" = "v1.8.0"
"golangci-lint" = "2.13.2"
"buf" = "1.72.0"
"tilt" = "0.37.7"
"protoc-gen-go" = "1.36.12"
"protoc-gen-connect-go" = "1.20.0"
"npm:@bufbuild/protoc-gen-es" = "2.14.1"
"npm:@connectrpc/protoc-gen-connect-query" = "2.3.1"
"npm:sfw" = "2.0.6"
