// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/varunbpatil/temporal-lens/domains/workflows/ports (interfaces: Mapper,WorkflowService,WorkflowSource,WorkflowRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/workflows.go -package=mocks github.com/varunbpatil/temporal-lens/domains/workflows/ports Mapper,WorkflowService,WorkflowSource,WorkflowRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	iter "iter"
	reflect "reflect"

	models "github.com/varunbpatil/temporal-lens/domains/workflows/models"
	ports "github.com/varunbpatil/temporal-lens/domains/workflows/ports"
	types "github.com/varunbpatil/temporal-lens/types"
	gomock "go.uber.org/mock/gomock"
)

// MockMapper is a mock of Mapper interface.
type MockMapper struct {
	ctrl     *gomock.Controller
	recorder *MockMapperMockRecorder
	isgomock struct{}
}

// MockMapperMockRecorder is the mock recorder for MockMapper.
type MockMapperMockRecorder struct {
	mock *MockMapper
}

// NewMockMapper creates a new mock instance.
func NewMockMapper(ctrl *gomock.Controller) *MockMapper {
	mock := &MockMapper{ctrl: ctrl}
	mock.recorder = &MockMapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMapper) EXPECT() *MockMapperMockRecorder {
	return m.recorder
}

// Map mocks base method.
func (m *MockMapper) Map(key string, value any) ports.Field {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Map", key, value)
	ret0, _ := ret[0].(ports.Field)
	return ret0
}

// Map indicates an expected call of Map.
func (mr *MockMapperMockRecorder) Map(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Map", reflect.TypeOf((*MockMapper)(nil).Map), key, value)
}

// Schema mocks base method.
func (m *MockMapper) Schema() types.Schema {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Schema")
	ret0, _ := ret[0].(types.Schema)
	return ret0
}

// Schema indicates an expected call of Schema.
func (mr *MockMapperMockRecorder) Schema() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Schema", reflect.TypeOf((*MockMapper)(nil).Schema))
}

// MockWorkflowService is a mock of WorkflowService interface.
type MockWorkflowService struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowServiceMockRecorder
	isgomock struct{}
}

// MockWorkflowServiceMockRecorder is the mock recorder for MockWorkflowService.
type MockWorkflowServiceMockRecorder struct {
	mock *MockWorkflowService
}

// NewMockWorkflowService creates a new mock instance.
func NewMockWorkflowService(ctrl *gomock.Controller) *MockWorkflowService {
	mock := &MockWorkflowService{ctrl: ctrl}
	mock.recorder = &MockWorkflowServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowService) EXPECT() *MockWorkflowServiceMockRecorder {
	return m.recorder
}

// DeleteIndex mocks base method.
func (m *MockWorkflowService) DeleteIndex(ctx context.Context, index string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIndex", ctx, index)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIndex indicates an expected call of DeleteIndex.
func (mr *MockWorkflowServiceMockRecorder) DeleteIndex(ctx, index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIndex", reflect.TypeOf((*MockWorkflowService)(nil).DeleteIndex), ctx, index)
}

// ListIndexes mocks base method.
func (m *MockWorkflowService) ListIndexes(ctx context.Context) ([]ports.IndexInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIndexes", ctx)
	ret0, _ := ret[0].([]ports.IndexInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIndexes indicates an expected call of ListIndexes.
func (mr *MockWorkflowServiceMockRecorder) ListIndexes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIndexes", reflect.TypeOf((*MockWorkflowService)(nil).ListIndexes), ctx)
}

// Reset mocks base method.
func (m *MockWorkflowService) Reset(ctx context.Context, req ports.ResetRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reset", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reset indicates an expected call of Reset.
func (mr *MockWorkflowServiceMockRecorder) Reset(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockWorkflowService)(nil).Reset), ctx, req)
}

// Search mocks base method.
func (m *MockWorkflowService) Search(ctx context.Context, req ports.SearchRequest) (ports.SearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, req)
	ret0, _ := ret[0].(ports.SearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockWorkflowServiceMockRecorder) Search(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockWorkflowService)(nil).Search), ctx, req)
}

// Signal mocks base method.
func (m *MockWorkflowService) Signal(ctx context.Context, req ports.SignalRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signal", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Signal indicates an expected call of Signal.
func (mr *MockWorkflowServiceMockRecorder) Signal(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockWorkflowService)(nil).Signal), ctx, req)
}

// Start mocks base method.
func (m *MockWorkflowService) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockWorkflowServiceMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockWorkflowService)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockWorkflowService) Stop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockWorkflowServiceMockRecorder) Stop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockWorkflowService)(nil).Stop), ctx)
}

// Terminate mocks base method.
func (m *MockWorkflowService) Terminate(ctx context.Context, req ports.TerminateRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Terminate", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Terminate indicates an expected call of Terminate.
func (mr *MockWorkflowServiceMockRecorder) Terminate(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Terminate", reflect.TypeOf((*MockWorkflowService)(nil).Terminate), ctx, req)
}

// MockWorkflowSource is a mock of WorkflowSource interface.
type MockWorkflowSource struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowSourceMockRecorder
	isgomock struct{}
}

// MockWorkflowSourceMockRecorder is the mock recorder for MockWorkflowSource.
type MockWorkflowSourceMockRecorder struct {
	mock *MockWorkflowSource
}

// NewMockWorkflowSource creates a new mock instance.
func NewMockWorkflowSource(ctrl *gomock.Controller) *MockWorkflowSource {
	mock := &MockWorkflowSource{ctrl: ctrl}
	mock.recorder = &MockWorkflowSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowSource) EXPECT() *MockWorkflowSourceMockRecorder {
	return m.recorder
}

// Reset mocks base method.
func (m *MockWorkflowSource) Reset(ctx context.Context, req ports.InternalResetRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reset", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reset indicates an expected call of Reset.
func (mr *MockWorkflowSourceMockRecorder) Reset(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockWorkflowSource)(nil).Reset), ctx, req)
}

// ResolveWorkflowTaskFinishEventID mocks base method.
func (m *MockWorkflowSource) ResolveWorkflowTaskFinishEventID(ctx context.Context, metadata models.WorkflowMetadata, activity ports.ResetSpecActivity) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveWorkflowTaskFinishEventID", ctx, metadata, activity)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveWorkflowTaskFinishEventID indicates an expected call of ResolveWorkflowTaskFinishEventID.
func (mr *MockWorkflowSourceMockRecorder) ResolveWorkflowTaskFinishEventID(ctx, metadata, activity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveWorkflowTaskFinishEventID", reflect.TypeOf((*MockWorkflowSource)(nil).ResolveWorkflowTaskFinishEventID), ctx, metadata, activity)
}

// Signal mocks base method.
func (m *MockWorkflowSource) Signal(ctx context.Context, req ports.InternalSignalRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signal", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Signal indicates an expected call of Signal.
func (mr *MockWorkflowSourceMockRecorder) Signal(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockWorkflowSource)(nil).Signal), ctx, req)
}

// StreamWorkflowData mocks base method.
func (m *MockWorkflowSource) StreamWorkflowData(ctx context.Context, req ports.StreamWorkflowDataRequest, mapper ports.Mapper) iter.Seq2[*models.WorkflowData, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamWorkflowData", ctx, req, mapper)
	ret0, _ := ret[0].(iter.Seq2[*models.WorkflowData, error])
	return ret0
}

// StreamWorkflowData indicates an expected call of StreamWorkflowData.
func (mr *MockWorkflowSourceMockRecorder) StreamWorkflowData(ctx, req, mapper any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamWorkflowData", reflect.TypeOf((*MockWorkflowSource)(nil).StreamWorkflowData), ctx, req, mapper)
}

// StreamWorkflowMetadata mocks base method.
func (m *MockWorkflowSource) StreamWorkflowMetadata(ctx context.Context, req ports.StreamWorkflowMetadataRequest) iter.Seq2[*models.WorkflowMetadata, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamWorkflowMetadata", ctx, req)
	ret0, _ := ret[0].(iter.Seq2[*models.WorkflowMetadata, error])
	return ret0
}

// StreamWorkflowMetadata indicates an expected call of StreamWorkflowMetadata.
func (mr *MockWorkflowSourceMockRecorder) StreamWorkflowMetadata(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamWorkflowMetadata", reflect.TypeOf((*MockWorkflowSource)(nil).StreamWorkflowMetadata), ctx, req)
}

// Terminate mocks base method.
func (m *MockWorkflowSource) Terminate(ctx context.Context, req ports.InternalTerminateRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Terminate", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Terminate indicates an expected call of Terminate.
func (mr *MockWorkflowSourceMockRecorder) Terminate(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Terminate", reflect.TypeOf((*MockWorkflowSource)(nil).Terminate), ctx, req)
}

// WorkflowURL mocks base method.
func (m *MockWorkflowSource) WorkflowURL(ctx context.Context, metadata models.WorkflowMetadata) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkflowURL", ctx, metadata)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WorkflowURL indicates an expected call of WorkflowURL.
func (mr *MockWorkflowSourceMockRecorder) WorkflowURL(ctx, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkflowURL", reflect.TypeOf((*MockWorkflowSource)(nil).WorkflowURL), ctx, metadata)
}

// MockWorkflowRepository is a mock of WorkflowRepository interface.
type MockWorkflowRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowRepositoryMockRecorder
	isgomock struct{}
}

// MockWorkflowRepositoryMockRecorder is the mock recorder for MockWorkflowRepository.
type MockWorkflowRepositoryMockRecorder struct {
	mock *MockWorkflowRepository
}

// NewMockWorkflowRepository creates a new mock instance.
func NewMockWorkflowRepository(ctrl *gomock.Controller) *MockWorkflowRepository {
	mock := &MockWorkflowRepository{ctrl: ctrl}
	mock.recorder = &MockWorkflowRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowRepository) EXPECT() *MockWorkflowRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockWorkflowRepository) Add(ctx context.Context, index string, workflows []*models.Workflow) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, index, workflows)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockWorkflowRepositoryMockRecorder) Add(ctx, index, workflows any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockWorkflowRepository)(nil).Add), ctx, index, workflows)
}

// CreateIndex mocks base method.
func (m *MockWorkflowRepository) CreateIndex(ctx context.Context, index string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIndex", ctx, index)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateIndex indicates an expected call of CreateIndex.
func (mr *MockWorkflowRepositoryMockRecorder) CreateIndex(ctx, index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIndex", reflect.TypeOf((*MockWorkflowRepository)(nil).CreateIndex), ctx, index)
}

// DeleteIndex mocks base method.
func (m *MockWorkflowRepository) DeleteIndex(ctx context.Context, index string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIndex", ctx, index)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIndex indicates an expected call of DeleteIndex.
func (mr *MockWorkflowRepositoryMockRecorder) DeleteIndex(ctx, index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIndex", reflect.TypeOf((*MockWorkflowRepository)(nil).DeleteIndex), ctx, index)
}

// ListIndexes mocks base method.
func (m *MockWorkflowRepository) ListIndexes(ctx context.Context) ([]ports.IndexInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIndexes", ctx)
	ret0, _ := ret[0].([]ports.IndexInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIndexes indicates an expected call of ListIndexes.
func (mr *MockWorkflowRepositoryMockRecorder) ListIndexes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIndexes", reflect.TypeOf((*MockWorkflowRepository)(nil).ListIndexes), ctx)
}

// Search mocks base method.
func (m *MockWorkflowRepository) Search(ctx context.Context, indexes []string, req ports.SearchRequest) (ports.SearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, indexes, req)
	ret0, _ := ret[0].(ports.SearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockWorkflowRepositoryMockRecorder) Search(ctx, indexes, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockWorkflowRepository)(nil).Search), ctx, indexes, req)
}
